---
- name: "update yum packages."
  become: true
  yum:
    update_cache: yes

- name: remove dependencies that are no longer required
  become: true
  yum:
    autoremove: yes

- name: "install dependencies."
  become: true
  yum:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy index test page
  copy:
    src: "index.js"
    dest: "~/web/index.js"

- name: Executing node
  shell: |
    pm2 start ~/web/index.js -f
